name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: |
          cd SpottoAPI.Tests
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal

      - name: Pack project
        run: |
          cd SpottoAPI
          dotnet build --no-restore
          dotnet pack -c Release -o out
      - name: Push generated package to NuGet
        run: dotnet nuget push ./SpottoAPI/out/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
